# |=================================================
# | HeroMagnata by Heroslender
# |-------------------------------------------------
# |
# |  Para uma explicacao mais detalhada acesse: http://heroslender.cf/plugins/HeroMagnata/
# |
# | acoes:
# | - [comando_consola] - Executar um comando pela consola
# | - [comando_antigo] - Fazer o magnata antigo executar um comando
# | - [comando_novo] - Fazer o novo magnata executar um comando
# | - [broadcast] - Enviar uma mensagem para o servidor
# | - [mensagem_antigo] - Enviar uma mensagem para o magnata antigo
# | - [mensagem_novo] - Enviar uma mensagem para o novo magnata
# | - [title_broadcast] - Enviar um title para o servidor
# | - [title_antigo] - Enviar um title para o magnata antigo
# | - [title_novo] - Enviar um title para o novo magnata
# | - [actionbar_broadcast] - Enviar um title para o novo magnata
# | - [actionbar_antigo] - Enviar um title para o novo magnata
# | - [actionbar_novo] - Enviar um title para o novo magnata
# |
# | PlaceHolders:
# | - {antigo_nome}
# | - {antigo_prefix}
# | - {antigo_suffix}
# | - {antigo_saldo}
# | - {antigo_saldo_short}
# | - {novo_nome}
# | - {novo_prefix}
# | - {novo_suffix}
# | - {novo_saldo}
# | - {novo_saldo_short}
# |
# |
# | # Nao e obrigatorio ter o LegendChat
# | # Tag no chat do LegendChat {magnata}
# | legendchat-tag: '&2[MAGNATA] '
# |
# | acoes:
# |   # Executa quando tem um novo magnata
# |   ativar: []
# |   # Executa quando o magnata entra no servidor
# |   entrar: []
# |   # Executa quando o magnata sai do servidor
# |   sair: []
# |
# | # Delay para procurar por um novo magnata - em segundos
# | delay-atualizar: 900
# |
# | # Valor usado nos placeholders saldo_short
# | # E possivel adicionar mais e remover
# | money-tags: K;M;B;T;Q
# | money-tags: ' Mil; Milhoes; Bilhoes; Ttrilhoes; Quadrilhoes'
# |
# |-------------------------------------------------
apenas-online: false
legendchat-tag: '&2[MAGNATA] '
comando-magnata: '&2[$] &aMagnata atual: &7{novo_prefix}{novo_nome}{novo_suffix} &8- &e{novo_saldo}'
acoes:
  ativar:
    - '[broadcast] &r'
    - '[broadcast] &2[Magnata] &a&l{novo_prefix}{novo_nome} &aE o novo magnata com um balanco de &a&l${novo_saldo}'
    - '[broadcast] &r'
    - '[title_broadcast] &2{novo_nome}{NL}&aE o novo magnata!'
  entrar:
    - '[broadcast] &2[Magnata] &a&l{novo_nome} &aentrou no servidor!'
  sair:
    - '[broadcast] &2[Magnata] &a&l{novo_nome} &asaiu do servidor'
delay-atualizar: 900
money-tags: K;M;B;T;Q