name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
author: Heroslender
softdepend: [Legendchat, HolographicDisplays, Citizens]

commands:
  magnata:
     description: Ver o magnata atual.
     usage: §c/<command>§7 - §eVer o magnata atual